### ISSUE TITLE
[Swoole] Profiler error (token not found) show when using Swoole Runtime

### ISSUE THREAD

**Issue by ad3n** [php-runtime/runtime#106]
<img width="1792" alt="Screen Shot 2021-11-30 at 20 18 31" src="https://user-images.githubusercontent.com/7464920/144054636-758030d3-1835-4696-b941-2d21917fd8d0.png">

How to produce:

Skeleton fresh install then add profiler and swoole runtime

**Comment by ging-dev** [comment]
Fixed by https://github.com/php-runtime/runtime/pull/86

**Comment by alexander-schranz** [comment]
@ging-dev thx for ping.
