### ISSUE TITLE
Layer information

### ISSUE THREAD

**Issue by jasonmccallister** [php-runtime/runtime#107]
When reading the docs on deploying a Bref runtime, there is a custom layer for PHP runtime. Bref provides a list of layer ARNs at https://runtimes.bref.sh. Is there somewhere similar the layer ARNs for the PHP runtimes are published?

**Comment by Nyholm** [comment]
Sorry for the late answer. Here is the information you are looking for: https://github.com/php-runtime/bref-layer#lambda-layers-in-details
