### ISSUE TITLE
Psr-17 does not work with Runtime 6.0 on PHP 8.0

### ISSUE THREAD

**Issue by yyeltsyn** [php-runtime/runtime#108]
Fatal error: Declaration of Runtime\Psr17\Runtime::getArgument(ReflectionParameter $parameter, ?string $type)
must be compatible with Symfony\Component\Runtime\GenericRuntime::getArgument(ReflectionParameter $parameter, ?string
$type): mixed in /srv/middleware/vendor/runtime/psr-17/src/Runtime.php on line 53

**Comment by alexander-schranz** [comment]
I think we would need add then:

```
: mixed
```

But the Problem is that we would then increase to PHP 8.0.

/cc @Nyholm what should we do here?

**Comment by Nyholm** [comment]
Oh. Yes. I think we should add that on all places.
