### ISSUE TITLE
Create a tag for Symfony 7 support

### ISSUE THREAD

**Issue by dunglas** [php-runtime/runtime#157]
Hi,

Would it be possible to create a new tag, at least for `runtime/frankenphp-symfony`?

Currently, it's not possible to install the package with Symfony 7, and breaks projects relying on FrankenPHP such as Symfony Docker.

Thanks!

**Comment by KDederichs** [comment]
Maybe, while you're at it it would be nice if you could merge in #155 and #156 as well? :)

**Comment by Nyholm** [comment]
Working on a release now. Just fixing CI first. 

Thank you for the ping

**Comment by dunglas** [comment]
Thank you!!
