### ISSUE TITLE
[Bref] Retrieve the authorization informations from api-gateway

### ISSUE THREAD

**Issue by DevMDamien** [php-runtime/runtime#77]
Hello,

I would like to retrieve the authorization informations from api-gateway when I'm using the bref runtime.

From a bref layer (for example `php-74-fpm`), I could retrieve this information with `$_SERVER['LAMBDA_REQUEST_CONTEXT']` (see [Bref\Event\Http\FpmHandler.php](https://github.com/brefphp/bref/blob/master/src/Event/Http/FpmHandler.php))

**Comment by Nyholm** [comment]
Excellent question!
If you are using a PSR-11 application you can get these from the `Context` object directly. However, if you are using a Symfony or Laravel kernel, then you will soon be able to get it by `$request->server->get('LAMBDA_REQUEST_CONTEXT')`.

~~I just added a PR to fix this.~~

I see that you just added #78. =)
